### ISSUE TITLE
Oskar part fails in Pinocchio Unittest

### ISSUE THREAD

**Issue by fschramka** [i4Ds/Karabo-Pipeline#128]
See https://github.com/i4Ds/Karabo-Pipeline/runs/7919966351?check_suite_focus=true

**Comment by cvoegele** [comment]
Does this also happen on your machine? Cause it is a 126 Killed Signal, so probably the OSKAR was using too many resources.

**Comment by deiruch** [comment]
Should be fixed by #151

**Comment by fschramka** [comment]
no it is still buggy - see https://github.com/i4Ds/Karabo-Pipeline/actions/runs/3174139636

changed some stuff in https://github.com/i4Ds/Karabo-Pipeline/commit/f1f95fc3298a7a442a36445f4f920f8bed88de74

new fail with exit code 137 - out of memory. The github runner has 7GB (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners). Will check if this test needs more.

**Comment by fschramka** [comment]
Local run needs up to 20GB 👍 clearly this is too much for the github runner. Will reduce the oskar workload.

**Comment by fschramka** [comment]
Even with lower settings the memory needs are above 16GB... @rohitcbscient you have any idea how to decrease this? 

@deiruch we could also remove this test - because it is clearly a github runner issue.

**Comment by rohitcbscient** [comment]
> Even with lower settings the memory needs are above 16GB... @rohitcbscient you have any idea how to decrease this?
- I think we do not need accurate results for the unit test, just a working result. If this is correct, you can reduce the image size from 4096*4 to 2048.

**Comment by deiruch** [comment]
We could also use [ReFrame](https://reframe-hpc.readthedocs.io/) and run tests on CSCS infra, if we need more resources. Do we have other tests where it would be useful to have more resources?

**Comment by deiruch** [comment]
Perhaps ask Victor Holanda (CSCS) on how to setup the infra to get automated CI/CD.
