### ISSUE TITLE
Example Code outdated

### ISSUE THREAD

**Issue by patoch01220** [i4Ds/Karabo-Pipeline#167]
Hello,
I am a student in computer sciences, and for my Master Thesis I would need to use Karabo.

Unfortunately, I can't install it...

I first tried following this page : https://i4ds.github.io/Karabo-Pipeline/installation_user.html
but when I run this command: ```conda install -c i4ds -c conda-forge karabo-pipeline``` I get this answer:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                        

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

I also tried installing all the dependencies on this link (https://i4ds.github.io/Karabo-Pipeline/installation_no_conda.html) and follow the first step but after running those commands:
```
brew tap ska-ska/tap #tap into repository where casacore is
brew update
brew install cmake git-lfs casacore boost
```
I don't get how I can run the ./install.sh as I don't have the karabo-pipeline installed on my PC.

I even installed OSKAR and Rascil manually, as it is explained on the same link but it didn't seems to change my issue.

What can I do please ? 

PS: I have the python 3.10.7 version and the 3.9.12

**Comment by fschramka** [comment]
Related to #125 - searching for a solution

**Comment by fschramka** [comment]
@patoch01220 

I did find the culprint. Until it is fixed, here is a workaround (only works if you do not use rascil):

1. Checkout this repo
2. Open the environment-dev.yaml file (ignore the environment-dev-mac.yaml)
3. Comment out rascil on line 8 (with a '#')
4. Create an dev environment with `conda env create -f environment-dev.yaml`

You can now use the Karabo Scripts directly (do not include them as a package).

**Comment by patoch01220** [comment]
@fschramka
Great thank you very much, I tried what you said by forking your repo and cloning it on my machine and do the changes you told me. 
It works just fine like this!

Anyways I still have to apply some small changes in my code compare to the one on your Example jupyter notebook, but still I can now get familiar with those tools.

Can I ask you if you will be able to fix this issue soon? I have a meeting with my proffessor soon and I will explain him what I've done so far and the issues I encontered. SoI thought it would be pertinent to have an idea if this issue would be resolved soon or not, so he can adapt the work he will assign to me for next weeks. 

Once again, thank you very much, I really appreciate your help!

**Comment by patoch01220** [comment]
Small update about my journey, 
I start trying to reproduce the Example notebook you gave and until now everything worked well. 

I reached the cell number 6 I think, containing this code:
```
observation_settings = observation.Observation(100e6,
                                               phase_centre_ra_deg=phase_center[0],
                                               phase_centre_dec_deg=phase_center[1],
                                               number_of_channels=64,
                                               number_of_time_steps=24)

interferometer_sim = interferometer.InterferometerSimulation(channel_bandwidth_hz=1e6)
visibility_askap = interferometer_sim.run_simulation(askap_tel, sky, observation_settings)
```

But when I run it it gives me the following error:
```
RuntimeError                              Traceback (most recent call last)
Cell In [61], line 8
      1 observation_settings = observation.Observation(100e6,
      2                                                phase_centre_ra_deg=phase_center[0],
      3                                                phase_centre_dec_deg=phase_center[1],
      4                                                number_of_channels=64,
      5                                                number_of_time_steps=24)
      7 interferometer_sim = interferometer.InterferometerSimulation(channel_bandwidth_hz=1e6)
----> 8 visibility_askap = interferometer_sim.run_simulation(askap_tel, sky, observation_settings)

File ~/Desktop/Patoch/Uni/2nd-Year/MasterThesis/master-thesis/Karabo-Pipeline/karabo/simulation/interferometer.py:115, in InterferometerSimulation.run_simulation(self, telescope, sky, observation)
    107 def run_simulation(self, telescope: Telescope, sky: SkyModel, observation: Observation) -> Visibility:
    108     """
    109     Run a singel interferometer simulation with the given sky, telescope.png and observation settings.
    110     :param telescope: telescope.png model defining the telescope.png configuration
    111     :param sky: sky model defining the sky sources
    112     :param observation: observation settings
    113     """
--> 115     os_sky = sky.get_OSKAR_sky()
    116     observation_settings = observation.get_OSKAR_settings_tree()
    117     input_telpath=telescope.path

File ~/Desktop/Patoch/Uni/2nd-Year/MasterThesis/master-thesis/Karabo-Pipeline/karabo/simulation/sky_model.py:447, in SkyModel.get_OSKAR_sky(self)
    441 def get_OSKAR_sky(self) -> oskar.Sky:
...
--> 344     raise RuntimeError("OSKAR library not found.")
    345 t = Sky()
    346 t.capsule = _sky_lib.from_array(array, precision)

RuntimeError: OSKAR library not found.
```

So i tried installing OSKAR (but It was already installed before) like you explained on this link: https://i4ds.github.io/Karabo-Pipeline/installation_no_conda.html which seemed to work.

I then checked and I do have Oskar in my applications, but this notebook cell still gave me the same error.

Could it be due to the issue I have with Rascil? And if not, do you have any idea on how I could solve this, because I honnestly have no idea.

Thank you very much!

**Comment by fschramka** [comment]
@patoch01220 
> PS: Would it be possible to keep me in touch once the problem would be solved?
Sure - I will post it the moment it is fixed :)

**Comment by fschramka** [comment]
@patoch01220 

The example code is outdated. If you check 

https://github.com/i4Ds/Karabo-Pipeline/blob/b29fcfc233f2b7b6e891b4199b6b82f0d060b638/karabo/simulation/observation.py#L28

then you can see, that an observation does not take an Integer (100e6 in your example) as the first argument :) Try this instead:

      1 observation_settings = observation.Observation(start_frequency_hz = 100e6,
      2                                                phase_centre_ra_deg = phase_center[0],
      3                                                phase_centre_dec_deg = phase_center[1],
      4                                                number_of_channels = 64,
      5                                                number_of_time_steps = 24)

But that does not solve your `344 raise RuntimeError("OSKAR library not found.")` problem which is most probably related to the whole macOS setup. We will track the macOS setup in #125 - this ticket will stay for the example code update. Please check the other ticket for updates to the setup.

**Comment by deiruch** [comment]
Should be fixed in dev.

**Comment by patoch01220** [comment]
> Should be fixed in dev.

I tried re Installing karabo with the command in the documentation but it still doesn't work. 

I have to following message: 
```
(karabo-env) patoch@patricks-mbp-1 ~ % conda install -c i4ds -c conda-forge karabo-pipeline

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by deiruch** [comment]
That the installation fails on macOS is expected. This work is tracked in #125. But the example code should be correct now. @patoch01220 is it correct that your problem is the installation on macOS, and not (yet) with incorrect example code?

**Comment by patoch01220** [comment]
> That the installation fails on macOS is expected. This work is tracked in #125. But the example code should be correct now. @patoch01220 is it correct that your problem is the installation on macOS, and not (yet) with incorrect example code?

Yes my issue is with the installation. For now I simply download the karabo folder and applied the changes specified above (https://github.com/i4Ds/Karabo-Pipeline/issues/167#issuecomment-1267274376) as a temporary solution and I allows me to still use the source detection (which is what I need).
But I would really appreciate if you could let me know when the installation problem would be solved

**Comment by deiruch** [comment]
Ah, I see. Ok, we'll track the installation issue in #125 and close this. I'll move your comment over there.
