### ISSUE TITLE
Fix RASCIL_DATA directory not found error in current RASCIL packages.

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#50]
The data directory env variable is not picked up in Jupyter kernels. Provide a better fix, like putting the directory at the correct destination without the need for a variable.

**Comment by cvoegele** [comment]
fixed by this https://github.com/i4Ds/Karabo-Pipeline/pull/60

**Comment by cvoegele** [comment]
Also this https://github.com/i4Ds/Karabo-Pipeline/pull/61

**Comment by Lukas113** [comment]
After I've done:
karabo.util.jupyter import setup_jupyter_env
setup_jupyter_env()

I still get the Error: OSError: RASCIL data directory /home/lukas/anaconda3/envs/karabo/lib/python3.8/site-packages/../../../rascil_data/data does not exist

This has beeen done after a fresh setup of my environment. The assignment of the environment variable seems to work. However, in this location the data folder still doesn't exist. I don't think it has something to do that I import the local modules instead of the karabo package from the site-packages (since my functions are not on the main branch/current release).

The current path seems to point at the venv directory. However, I think we need another solution. Since it is not the last import in the rascil code and we can't just catch the error during the import, we either have to describe the setup of the data download in our documentation (or point to rascil documentation) or we do the download during the setup.

**Comment by cvoegele** [comment]
Pull Request #77 should fix this issue now. The RASCIL Packages has been updated aswell.
I would however be happy, if someone else could also start the object_detection.ipynb in a new environment based of the enivornment-dev.yml file. To make sure the new RASCIL Packges is freshly installed

`conda env create -f environment-dev.yml`
`conda install -c conda-forge jupyter`
`conda activate karabo_dev_env`
Start jupyter lab
run the notebook

**Comment by rohitcbscient** [comment]
Tested ok my PC. No error on RASCIL_DATA was found.
